added 6 tasks
Sibir-Yak/git-init pull request #3
Opened 2022-08-11 08:44 UTC by Sibir-Yak

2022-08-13 08:33 UTC, d1ma-angel requested changes

2022-08-13 08:33 UTC, d1ma-angel commented on 1_100.rb
> +num = (2..20).map { |n| n*5 }
Не наглядно. Откуда ты взял магические числа 2 и 20? Их не было в задании. У тебя были только 10 и 100.

2022-08-13 08:33 UTC, d1ma-angel commented on mounts.rb
> +     if day == 30
Принято, но следи за отступами

2022-08-13 08:33 UTC, d1ma-angel commented on fibonaci.rb
> +    puts f1
Нужно заполнить ими массив, а не вывести на экран
Отступы

2022-08-13 08:33 UTC, d1ma-angel commented on leap_year.rb
> +    shit = 0
Обрати внимание у тебя строки с 15 по 22 повторяются 3 раза. Лучше за счет условий (if) назначай разные значения для years, а одинаковые действия выполняй единожды.
Более того у тебя и хеш с месяцами почти полностью повторяется (кроме февраля). Можно просто устанавливать разные значения для числа дней в феврале, как работать с хешами ты уже знаешь.

2022-08-13 08:33 UTC, d1ma-angel commented on market.rb
> +user_input = nil
1. а зачем они тебе тут? я про user_input-ы
2. и старайся всегда называть переменные так, чтобы сходу можно было понять, что в ней лежит. Да, я понимаю, что это пользовательский ввод, но так лежит или название товара, или его цена, или его количество.

2022-08-13 08:33 UTC, d1ma-angel commented on market.rb
> +loop do
Смотри, давай разобьем эту задачу на части.
1. Ты узнаешь у пользователя, что он купил и заполняешь хеш по принципу `{ product1: { price1: qty1 }, product2: { price2: qty2 } }`
2. Вторая часть. Ты проходишься по этому хешу и выводишь на экран итоговую сумму за каждый товар. Можешь одновременно тут считать общую сумму покупок.
3. Третья часть. Или сразу выводишь общую сумму покупок если посчитал ее в части 2 или считаешь и выводишь по примеру 2 части.

2022-08-16 14:50 UTC, Sibir-Yak commented on fibonaci.rb
> +    puts f1
что не так с отступами здесь ?  Где не правильно?

2022-10-04 10:19 UTC, merged