task number 4
Sibir-Yak/git-init pull request #5
Opened 2022-11-16 14:22 UTC by Sibir-Yak

2022-11-28 21:18 UTC, d1ma-angel requested changes

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    @trains.each { |train| puts train.number }
Вынеси в отдельный метод, который будет выводить красиво список поездов с нумераций по принципу `1) ...`  и примени везде, где встречается такое выражение

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +      @stations.each { |station| puts station.names }
Вынеси в отдельный метод, который будет выводить красиво список станций с нумераций по принципу `1) ...`  и примени везде, где встречается такое выражение

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    if direction == 1
Используй `case..when..else` везде, где будет подобная логика

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +  attr_reader :wagons
можно объединить в одну строку

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +        menu2
старайся называть имена функций, чтобы сходу можно было понять, что они делают

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    number = gets.chomp.to_i
старайся называть имена переменных, чтобы сходу можно было понять, что в них хранится

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +      puts "Введите номер поезда"
нужно вынести до ветвления

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/train.rb
>      @type = type
избавиться от `type` по причине того, что у тебя класс уже отражает тип поезда. Везде где важно обращение к типу использовать именно сам класс, а не свойство `type`

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +      @trains.each do |train|
переделать с помощью метода `.select` или `.reject`

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    if @trains[train_add_wagon].type == "pass"
избавиться от обращения к type

2022-11-28 21:18 UTC, d1ma-angel commented on lesson3/train.rb
> +  def docking(wagon)         #стыковка  вагона
проверять чтобы можно было стыковать Только вагон соответствующий типу поезда

2022-12-02 09:53 UTC, Sibir-Yak commented on lesson3/train.rb
> +  def docking(wagon)         #стыковка  вагона
Теперь у меня вагоны добавляются методом. У грузового свой метод у пассажирского свой.

2022-12-02 09:54 UTC, Sibir-Yak commented on lesson3/railroad.rb
> +      @trains.each do |train|
не пойму как этот метод мне помог в данной ситуёвине

2022-12-02 09:55 UTC, Sibir-Yak commented on lesson3/train.rb
>      @type = type
избавился всё работает но как мне кажется условия ТЗ не выполняются

2022-12-10 09:00 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    break if user_choice == 0
У тебя 2 поведения на тот случай если чел введет 0. И один из них никогда не сработает.

2022-12-10 09:02 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    if num4 == 1
Чего тут не case..when? Ну и везде ты писал user_choice, а тут просто num4

2022-12-10 09:03 UTC, d1ma-angel commented on lesson3/railroad.rb
> +          puts "На станции #{station_for_train} находится поезд номер #{train_for_station}"
Если ты используешь переменную только 1 раз, то можно отдельно ее не создавать, а просто в месте вывода вызвать. Но, опять же, в разумных пределах

2022-12-10 09:05 UTC, d1ma-angel commented on lesson3/railroad.rb
> +    @stations.each do |station|
Уважаемо, нравится. Небольшая идея на будущее - посмотри метод .with_index(num)
В твоем случае это бы выглядело @stations.each.with_index(1) do |station, index|

2022-12-10 09:08 UTC, d1ma-angel commented on lesson3/railroad.rb
> +        puts "Добавили"
Соблюдай логику: сначала делаем, потом оповещаем пользака. Иначе он реально будет думать, что станция добавлена, а в следующей строке что-то поломается. И у него в голове будут неверные исходные данные. Он будет думать, что что-то поломаломась, потому что эта станция оказалась на маршруте, а не в процессе ее добавления.

2022-12-10 13:10 UTC, Sibir-Yak commented on lesson3/railroad.rb
> +    if num4 == 1
ленивая жопа я думал пусть хоть в одном месте будет для разнообразия

2022-12-10 15:44 UTC, Sibir-Yak commented on lesson3/railroad.rb
> +        puts "Добавили"
Долго думал , но потом когда выкнул смеялся =))) Так просто а я голову ломал. 
Полностью согласен !

2022-12-22 09:31 UTC, merged